export demo_home=${PWD}
export prefix=s1p-pks- ##ADD A PREFIX FOR GCP OBJECTS SUCH AS TEST-
export network=s1p-pks-net ## ADD NAME OF NETWORK
export subnet_ip_prefix="192.168.5" # Your subnet pref
export project_id=$(gcloud config get-value project)
export region=us-east1 # region that you will deploy Kubo in
export zone=us-east1-b # zone that you will deploy Kubo in
export kubo_envs=~/kubo-env
export kubo_env_name=kubo
export kubo_env_path="${kubo_envs}/${kubo_env_name}"
export kubo_cluster_name="pks-odb"
